# Generated by Django 3.1.4 on 2020-12-17 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('props_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='full_name',
        ),
    ]
