# Generated by Django 3.1.4 on 2021-01-05 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('props_app', '0003_auto_20210103_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_img',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
